# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sun, 19 Jul 2015 16:11:50 +0000
*               @ALL          1
*               @user         8
