<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: xyan
 * Date: Sun, 19 Jul 2015 21:16:01 +0200
 */

$conf['title'] = 'Little World - Team';
$conf['license'] = '0';
$conf['useheading'] = '1';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'revisions,search,register,subscribe,unsubscribe';

// end auto-generated content
